### ISSUE TITLE
[Site]: commit leads to ci failure

### ISSUE THREAD

**Issue by yuluo-yx** [apache/fury-site#155]
### Current State

**Description of the current issue**:

![image](https://github.com/user-attachments/assets/1c15ac8a-6b97-41e0-b2fb-4406f571703f)

I found that this commit synchronizes the document, changing the format of the document and causing the CI to fail.

### Desired State

**Description of the change you are proposing**:

Documents that should not be synchronized or synchronized in the correct format

### Would you like to fix this issue?

Yes! Please assign to me!

**Comment by yuluo-yx** [comment]
@chaokunyang Can you say what this ci task is for?

**Comment by chaokunyang** [comment]
As said in https://github.com/apache/fury-site/pull/148#issuecomment-2293424652, we have an automatic task to sync documents from https://github.com/apache/fury into this repository

**Comment by yuluo-yx** [comment]
sure, I'll do it.
