### ISSUE TITLE
[Site]: broken JavaScript icon at https://fury.apache.org/

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury-site#179]
### Current State

**Description of the current state**:
broken JavaScript icon at https://fury.apache.org/ introduced in #177
**Link to the wensite page, allow developers to better understand the problem**:
https://fury.apache.org/
**Screenshots (if relevant)**:
![image](https://github.com/user-attachments/assets/e792da21-fbb5-443b-b11e-15d0efaff072)

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by LofiSu** [comment]
Assign it to me. I'll do it
