### ISSUE TITLE
[Site]: add a copy button to home page code

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury-site#180]
### Current State

**Description of the current state**:
add a copy button to home page code: https://fury.apache.org/

**Link to the wensite page, allow developers to better understand the problem**:
https://fury.apache.org/

**Screenshots (if relevant)**:
![image](https://github.com/user-attachments/assets/62b504ed-0008-46d6-a58e-945f18ab5755)

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by LofiSu** [comment]
Assign it to me. I'll do it
