### ISSUE TITLE
[Site]: language quick start Button lost language path

### ISSUE THREAD

**Issue by chaokunyang** [apache/fury-site#182]
### Current State

**Description of the current state**:
When I click language button in:
![image](https://github.com/user-attachments/assets/bee0cdd1-9b11-4aab-be4e-b296442b9b70)

It just go to https://fury.apache.org/docs/start/usage/#rust instead of https://fury.apache.org/zh-CN/docs/start/usage/#rust

**Link to the wensite page, allow developers to better understand the problem**:

**Screenshots (if relevant)**:
![image](https://github.com/user-attachments/assets/84447acd-7057-4e7d-9588-e342b8875095)

### Desired State

**Description of the change you are proposing**:
Go to https://fury.apache.org/zh-CN/docs/start/usage/#rust, we need to carry locale path

### Would you like to fix this issue?

None

**Comment by LofiSu** [comment]
I will fix this problem
